---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    apt:
#      update_cashe: yes

  - name: remove apache from CentOS
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"
